// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateHeadCountLog(ctx context.Context, arg CreateHeadCountLogParams) (HeadCountLog, error)
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSnapshot(ctx context.Context, id uuid.UUID) (Snapshot, error)
	DeleteSource(ctx context.Context, id uuid.UUID) (Source, error)
	GetAuditLogs(ctx context.Context) ([]AuditLog, error)
	GetAuditLogsByUser(ctx context.Context, userID uuid.UUID) ([]AuditLog, error)
	GetHeadCountLogBySource(ctx context.Context, sourceID uuid.UUID) ([]HeadCountLog, error)
	GetSnapshotById(ctx context.Context, id uuid.UUID) (Snapshot, error)
	GetSnapshotsBySource(ctx context.Context, sourceID uuid.UUID) ([]Snapshot, error)
	GetSourceByID(ctx context.Context, id uuid.UUID) (Source, error)
	GetSources(ctx context.Context) ([]Source, error)
	GetSourcesId(ctx context.Context) ([]uuid.UUID, error)
	GetUserByEmailUsername(ctx context.Context, username string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
