// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    user_id,
    action,
    table_name,
    old_value,
    new_value
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateAuditLogParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Action    Audittype `json:"action"`
	TableName string    `json:"table_name"`
	OldValue  []byte    `json:"old_value"`
	NewValue  []byte    `json:"new_value"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.TableName,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const createHeadCountLog = `-- name: CreateHeadCountLog :one
INSERT INTO head_count_logs (
    source_id,
    head_count,
    current_fps,
    timestamp
) VALUES (
    $1, $2, $3, $4
) RETURNING id, source_id, head_count, current_fps, created_at, timestamp
`

type CreateHeadCountLogParams struct {
	SourceID   uuid.UUID        `json:"source_id"`
	HeadCount  int32            `json:"head_count"`
	CurrentFps float64          `json:"current_fps"`
	Timestamp  pgtype.Timestamp `json:"timestamp"`
}

func (q *Queries) CreateHeadCountLog(ctx context.Context, arg CreateHeadCountLogParams) (HeadCountLog, error) {
	row := q.db.QueryRow(ctx, createHeadCountLog,
		arg.SourceID,
		arg.HeadCount,
		arg.CurrentFps,
		arg.Timestamp,
	)
	var i HeadCountLog
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.HeadCount,
		&i.CurrentFps,
		&i.CreatedAt,
		&i.Timestamp,
	)
	return i, err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (
    source_id,
    image_path,
    head_count_at_time
) VALUES (
    $1, $2, $3
)
RETURNING id, source_id, image_path, head_count_at_time, created_at
`

type CreateSnapshotParams struct {
	SourceID        uuid.UUID `json:"source_id"`
	ImagePath       string    `json:"image_path"`
	HeadCountAtTime int32     `json:"head_count_at_time"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot, arg.SourceID, arg.ImagePath, arg.HeadCountAtTime)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ImagePath,
		&i.HeadCountAtTime,
		&i.CreatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (
    name,
    type,
    url,
    fps_target,
    resolution,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, type, url, fps_target, resolution, status, created_at
`

type CreateSourceParams struct {
	Name       string     `json:"name"`
	Type       Sourcetype `json:"type"`
	Url        string     `json:"url"`
	FpsTarget  int32      `json:"fps_target"`
	Resolution string     `json:"resolution"`
	Status     bool       `json:"status"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.FpsTarget,
		arg.Resolution,
		arg.Status,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.FpsTarget,
		&i.Resolution,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password,
    first_name,
    last_name
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, username, email, password, first_name, last_name
`

type CreateUserParams struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const deleteSnapshot = `-- name: DeleteSnapshot :one
DELETE FROM snapshots WHERE id = $1
RETURNING id, source_id, image_path, head_count_at_time, created_at
`

func (q *Queries) DeleteSnapshot(ctx context.Context, id uuid.UUID) (Snapshot, error) {
	row := q.db.QueryRow(ctx, deleteSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ImagePath,
		&i.HeadCountAtTime,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :one
DELETE FROM sources WHERE id = $1
RETURNING id, name, type, url, fps_target, resolution, status, created_at
`

func (q *Queries) DeleteSource(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, deleteSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.FpsTarget,
		&i.Resolution,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT id, user_id, action, table_name, old_value, new_value, created_at FROM audit_logs
`

func (q *Queries) GetAuditLogs(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.TableName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByUser = `-- name: GetAuditLogsByUser :many
SELECT id, user_id, action, table_name, old_value, new_value, created_at FROM audit_logs WHERE user_id = $1
`

func (q *Queries) GetAuditLogsByUser(ctx context.Context, userID uuid.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.TableName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeadCountLogBySource = `-- name: GetHeadCountLogBySource :many
SELECT id, source_id, head_count, current_fps, created_at, timestamp FROM head_count_logs WHERE source_id = $1
`

func (q *Queries) GetHeadCountLogBySource(ctx context.Context, sourceID uuid.UUID) ([]HeadCountLog, error) {
	rows, err := q.db.Query(ctx, getHeadCountLogBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeadCountLog
	for rows.Next() {
		var i HeadCountLog
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.HeadCount,
			&i.CurrentFps,
			&i.CreatedAt,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshotById = `-- name: GetSnapshotById :one
SELECT id, source_id, image_path, head_count_at_time, created_at FROM snapshots WHERE id = $1
`

func (q *Queries) GetSnapshotById(ctx context.Context, id uuid.UUID) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotById, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ImagePath,
		&i.HeadCountAtTime,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshots = `-- name: GetSnapshots :many
SELECT id, source_id, image_path, head_count_at_time, created_at FROM snapshots
`

func (q *Queries) GetSnapshots(ctx context.Context) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, getSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ImagePath,
			&i.HeadCountAtTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshotsBySource = `-- name: GetSnapshotsBySource :many
SELECT id, source_id, image_path, head_count_at_time, created_at FROM snapshots WHERE source_id = $1
`

func (q *Queries) GetSnapshotsBySource(ctx context.Context, sourceID uuid.UUID) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, getSnapshotsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ImagePath,
			&i.HeadCountAtTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, name, type, url, fps_target, resolution, status, created_at FROM sources WHERE id = $1
`

func (q *Queries) GetSourceByID(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.FpsTarget,
		&i.Resolution,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSources = `-- name: GetSources :many
SELECT id, name, type, url, fps_target, resolution, status, created_at FROM sources
`

func (q *Queries) GetSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, getSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.FpsTarget,
			&i.Resolution,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSourcesId = `-- name: GetSourcesId :many
SELECT id FROM sources
`

func (q *Queries) GetSourcesId(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getSourcesId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmailUsername = `-- name: GetUserByEmailUsername :one
SELECT id, username, email, password, first_name, last_name FROM users WHERE username = $1 OR email = $1
`

func (q *Queries) GetUserByEmailUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password, first_name, last_name FROM users WHERE Id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET
    name = $2,
    type = $3,
    url = $4,
    fps_target = $5,
    resolution = $6,
    status = $7
WHERE id = $1
RETURNING id, name, type, url, fps_target, resolution, status, created_at
`

type UpdateSourceParams struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Type       Sourcetype `json:"type"`
	Url        string     `json:"url"`
	FpsTarget  int32      `json:"fps_target"`
	Resolution string     `json:"resolution"`
	Status     bool       `json:"status"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.FpsTarget,
		arg.Resolution,
		arg.Status,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.FpsTarget,
		&i.Resolution,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = $2,
    email = $3,
    first_name = $4,
    last_name = $5
WHERE Id = $1
RETURNING id, username, email, password, first_name, last_name
`

type UpdateUserParams struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
